name: Personal Wiki Setup
permalink: /:title

url: chenliyo99.github.io
baseurl: /Personal-Wiki-Site-Setup
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

defaults:
  -
    scope:
      path: ""
    values:
      twitter_username: "your username"
      ga_id: "Your google analytics id"
    scope:
      path: "wiki/" # an empty string here means all files in the project
    values:
      importance: 5
      layout: post
      
